apiVersion: v1
kind: Pod
metadata:
  name: nginx-cpuinfo
  labels:
    app: nginx-cpuinfo
  annotations:
spec:
  containers:
  - name: nginx
    image: nginx
    command: [ "bash", "-c", "cat /proc/cpuinfo > /usr/share/nginx/html/index.html; nginx -g 'daemon off;'" ]
    ports:
    - containerPort: 80